server:
  port: 8516
spring:
  application:
    name: xbin-store-cloud-service-notify
  datasource:
            type: com.zaxxer.hikari.HikariDataSource
            driver-class-name: com.mysql.jdbc.Driver
            platform: mysql
            url: jdbc:mysql://154.8.147.101:3306/shop_demo?characterEncoding=utf-8
            username: guest
            password: mysql@2018!
            hikari:
               connectionTimeout: 30000
               idleTimeout: 600000
               maximumPoolSize: 60
               minimumIdle: 10
  redis:
    host: 127.0.0.1
    password:
    port: 6379

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

##eureka conf
eureka:
  client:
    serviceUrl:
      defaultZone: http://cloud.xbin.store.com:8501/eureka/
swagger2:
  package: cn.binux.notify.service
# Redis
redisKey:
  # 缓存时间 默认半小时
  expire_time: 3600
  prefix:
    # 号码登录次数前缀
    mobile_login_time:
      key: 'MOBILE_LOGIN_TIME:'
      expire_time: 3600
    # 号码code前缀
    mobile_login_code:
      key: 'MOBILE_LOGIN_CODE:'
      expire_time: 120

# Redis 一段时间允许发送几条短信
mobile_number_ceiling: 3
