server:
  port: 8501

spring:
  application:
    name: xbin-store-cloud-eureka-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://cloud.xbin.store.com:8501/eureka/
  instance:
    ##当hostname 为空时,使用192.168.1.115来补充;
    hostname: ${hostname:192.168.1.170}
